server:
  port: 18080

# 回写 SQL 接口（调用外部 arap 服务）
writeback-sql:
  api-url: http://arap.test-tx-16.e7link.com/arap/gen/debug/writeBackField2sql
  tenant-id: 711FNX50G6V0009

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testapp
#    url: jdbc:postgresql://postgres.test-tx-16.e7link.com:5432/tenant-public
    username: postgres
    password: 123
#    password: stet44{czars
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      INDENT_OUTPUT: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: INFO
    com.deepmodel.relation: DEBUG
